// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDEx5Az_6Z0kam0gtg1I3CLOUOftjjk18',
    appId: '1:327991919086:web:41d0db850154bd80284eff',
    messagingSenderId: '327991919086',
    projectId: 'chat-app-61d6d',
    authDomain: 'chat-app-61d6d.firebaseapp.com',
    storageBucket: 'chat-app-61d6d.appspot.com',
    measurementId: 'G-5Y0YK8R6S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_OLvWjVka1ixfIo9yIUBqssrxOr45P0c',
    appId: '1:327991919086:android:0c54ace2f727dc85284eff',
    messagingSenderId: '327991919086',
    projectId: 'chat-app-61d6d',
    storageBucket: 'chat-app-61d6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFtOSNYw_VG9tfnOakKB9M2w7vmfgxMpQ',
    appId: '1:327991919086:ios:d893acc2aa990c66284eff',
    messagingSenderId: '327991919086',
    projectId: 'chat-app-61d6d',
    storageBucket: 'chat-app-61d6d.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFtOSNYw_VG9tfnOakKB9M2w7vmfgxMpQ',
    appId: '1:327991919086:ios:0226c059cad0dc6a284eff',
    messagingSenderId: '327991919086',
    projectId: 'chat-app-61d6d',
    storageBucket: 'chat-app-61d6d.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
